name: action-seqera-launch
author: Phil Ewels

description: Launch a workflow using Seqera Platform (https://cloud.seqera.io/)

branding:
  icon: "play"
  color: "purple"

inputs:
  access_token:
    description: Seqera Platform access token (supports both SEQERA_ACCESS_TOKEN and TOWER_ACCESS_TOKEN secrets for compatibility)
    required: true
  compute_env:
    description: Seqera Platform compute environment name
    required: false
  workspace_id:
    description: Seqera Platform workspace ID
    required: false
  api_endpoint:
    description: Seqera Platform API URL
    required: false
    default: https://api.cloud.seqera.io
  pipeline:
    description: Pipeline repository
    default: https://github.com/${{ github.repository }}
    required: false
  revision:
    description: Pipeline revision (release / branch)
    required: false
  workdir:
    description: Nextflow work directory
    required: false
  parameters:
    description: Pipeline parameters
    required: false
    default: ''
  profiles:
    description: Nextflow config profiles
    required: false
  run_name:
    description: Seqera Platform run name
    required: false
  nextflow_config:
    description: Nextflow config options
    required: false
  pre_run_script:
    description: Pre-run script before launch
    required: false
  labels:
    description: Workflow labels (comma-separated)
    required: false
  wait:
    description: Set GitHub action to wait for pipeline completion
    default: false
    required: false
  debug:
    description: Enable debug logging for troubleshooting
    default: false
    required: false

outputs:
  json:
    description: JSON from Seqera Platform launch with workflowID, workflowUrl, workspaceId, workspaceRef
  workflowId:
    description: Unique ID of the pipeline run in Seqera Platform.
  workflowUrl:
    description: URL to pipeline run in Seqera Platform.
  workspaceId:
    description: Unique ID of workspace in Seqera Platform in which the pipeline is running.
  workspaceRef:
    description: Human readable format of workspace in Seqera Platform in format '[ organisation / workspace ]'.

runs:
  using: "node20"
  main: "dist/index.js"
