name: action-tower-launch
author: Phil Ewels

description: Launch a workflow using Seqera Platform (https://cloud.seqera.io/)

branding:
  icon: "play"
  color: "purple"

inputs:
  access_token:
    description: Seqera Platform access token
    required: true
  compute_env:
    description: Seqera Platform compute env
    required: false
  workspace_id:
    description: Seqera Platform workspace ID
    required: false
  api_endpoint:
    description: Seqera Platform API URL
    required: false
    default: https://api.cloud.seqera.io
  pipeline:
    description: Pipeline repository
    default: https://github.com/${{ github.repository }}
    required: false
  revision:
    description: Pipeline revision (release / branch)
    required: false
  workdir:
    description: Nextflow work directory
    required: false
  parameters:
    description: Pipeline parameters
    required: false
    default: ''
  profiles:
    description: Nextflow config profiles
    required: false
  run_name:
    description: Seqera Platform Run Name
    required: false
  nextflow_config:
    description: Nextflow config options
    required: false
  pre_run_script:
    description: Pre-run script before launch
    required: false
  wait:
    description: Set GitHub action to wait for pipeline completion
    default: false
    required: false

outputs:
  json:
    description: JSON from tw launch with workflowID, workflowUrl, workspaceId, workspaceRef
  workflowId:
    description: Unique ID of the pipeline run in Seqera Platform.
  workflowUrl:
    description: URL to pipeline run in Seqera Platform.
  workspaceId:
    description: Unique ID of workspace in Seqera Platform in which the pipeline is running.
  workspaceRef:
    description: Human readable format of workspace in Seqera Platform in format '[ organisation / workspace ]'.

runs:
  using: "docker"
  image: Dockerfile
  env:
    TOWER_WORKSPACE_ID: ${{ inputs.workspace_id }}
    TOWER_API_ENDPOINT: ${{ inputs.api_endpoint }}
    TOWER_ACCESS_TOKEN: ${{ inputs.access_token }}
    TOWER_COMPUTE_ENV: ${{ inputs.compute_env }}
    PIPELINE: ${{ inputs.pipeline }}
    REVISION: ${{ inputs.revision }}
    WORKDIR: ${{ inputs.workdir }}
    PARAMETERS: ${{ inputs.parameters != '' && toJson(fromJson(inputs.parameters)) || '' }}
    CONFIG_PROFILES: ${{ inputs.profiles }}
    RUN_NAME: ${{ inputs.run_name }}
    NEXTFLOW_CONFIG: ${{ inputs.nextflow_config }}
    PRE_RUN_SCRIPT: ${{ inputs.pre_run_script }}
    WAIT: ${{ inputs.wait }}
