name: CI/CD Action

on:
  push:
    branches:
      - dev
      - main
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  run-tower:
    name: Launch on Nextflow Tower
    # Don't try to run on forked repos
    if: github.repository == 'seqeralabs/action-tower-launch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        id: runs
        # Use repository secrets for sensitive fields
        with:
          pipeline: hello_world
          revision: master
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          run_name: ${{ github.job }}_${{ github.sha }}
          workdir: ${{ secrets.AWS_S3_BUCKET }}/work/${{ github.sha }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ### 🚀 Pipeline launched, monitor progress [here](${{ steps.runs.outputs.workflowUrl }}).

            | Name | Info |
            |------|------|
            | 🔨 Workflow ID | `${{ steps.runs.outputs.workflowId }}` |
            | 🏠 Workspace | `${{ steps.runs.outputs.workspaceRef }}` |
            | 🗂️ Workspace ID | `${{ steps.runs.outputs.workspaceId }}` |
            | 😎 Workflow URL | ${{ steps.runs.outputs.workflowUrl }} |
          comment_tag: towerrun
        if: github.event_name == 'pull_request'
      
      - uses: ./
        id: runfails
        continue-on-error: true
        with:
          pipeline: no_pipeline_exists
          revision: master
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          run_name: ${{ github.job }}_${{ github.sha }}
          workdir: ${{ secrets.AWS_S3_BUCKET }}/work/${{ github.sha }}

      - name: Check Failure
        if: steps.runfails.outcome == 'success'
        run: |
          echo "Failed to catch invalid pipeline submission: ${{ steps.runfails.outcome }}"
          exit 1

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}_run_json
          path: tower_action_*.json

      - uses: actions/upload-artifact@v3
        with:
          name: Tower debug log file
          path: tower_action_*.log
